input {
  beats {
    host => "0.0.0.0"
    port => 5044
  }
}

filter {
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password=> "#{Ff6windy098}"
    index => "filebeat-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
